config/routes.rb
YoolkReport::Application.routes.draw do
  root "reports#index"
  resources :reports

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  establish_connection("remote_database")

  def self.total_customers_by_date(start_date, end_date)
    where(created_at: start_date..end_date)
  end
end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessor :start_date, :end_date

  def self.r_customer_by_date(start_date, end_date)
    Listing.total_customers_by_date(start_date, end_date) if start_date.present?
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @reports = Report.all
  end

  def new
    @report = Report.new
  end

  def create
    @report = Report.new(set_params)
    if @report.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @report = Report.find(params[:id])
  end

  def edit
  end

  def update
    @report = Report.find(params[:id])
    @report_start_date = params[:report][:start_date]
    @report_end_date = params[:report][:end_date]
    @reports = Listing.total_customers_by_date(@report_start_date, @report_end_date)
    render 'customers_by_date_report'
  end

private

  def set_params
    params.require(:report).permit(:report_name, :report_description)
  end

  def set_date_range_params
    params.require(:report).permit(:start_date, :end_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YoolkReport</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="row">
    <div class="col-md-1">
    </div>
    <div class="col-md-11">
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/reports/_form.html.haml
= simple_form_for(Report.new, :defaults => { :wrapper_html => {:class => 'form-group'}, :input_html => { :class => 'form-control' } }) do |f|
  %p
    = f.input :report_name
  %p
    = f.input :report_description
  %p
    = f.submit 'Save', class: 'btn btn-success'

app/views/reports/customers_by_date_report.html.haml
.row
  .col-md-11
    %h2
      = @report.report_name
.row
  .col-md-11
    %table.table.table-striped
      %tr
        %th
          %p Name
        %th
          %p Address
        %th
          %p Bussiness Type ID
        %th
          %p Portal ID
      - @reports.each do |report|
        %tr
          %td
            = report.name
          %td
            = report.address
          %td
            = report.business_type_uuid
          %td
            = report.portal_uuid
      %tr
        %td{colspan: "4"}
          %p.active
            %span
              %strong
                Total customer for #{@report_start_date} ~ #{@report_end_date} ::
            %span
              %h2
                = @reports.size

      %tr
        %td{colspan: "4"}
          = link_to "Back", root_path, class: 'btn btn-primary'

app/views/reports/index.html.haml
.row
  .col-md-11
    %h1 Report Listing
.row
  .col-md-8
    %ul.list-group
      - @reports.each do |report|
        %li.list-group-item
          = link_to report.report_name, report_path(report)
  .col-md-2
    / Button trigger modal
    %button.btn.btn-info{"data-target" => "#reportForm", "data-toggle" => "modal"}
      Launch Report Form
    / Modal
    #reportForm.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
      .modal-dialog
        .modal-content
          .modal-header
            %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
            %h4#myModalLabel.modal-title New Report Form
          .modal-body
            = render 'form'
          .modal-footer
            %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
        / /.modal-content
      / /.modal-dialog
    / /.modal

app/views/reports/new.html.haml
= render 'form'

app/views/reports/show.html.haml
.row
  .col-md-11
    %h2
      = @report.report_name
.row
  .col-md-11
    = simple_form_for(@report, :defaults => { :wrapper_html => {:class => 'form-group'}, :input_html => { :class => 'form-control' } }) do |f|

      = f.input :start_date, :input_html => { :data => {:behaviour => :datepicker} },  placeholder: "Date Range [Start Date]"

      = f.input :end_date, :input_html => { :data => { :behaviour => :datepicker } }, placeholder: "Date Range [End Date]"

      = link_to "Back", root_path, class: "btn btn-primary"

      = f.submit 'Generate Detail Report', class: "btn btn-info"
      / = f.submit 'Generate Summary Report', class: "btn btn-info"

:javascript
  $('[data-behaviour~=datepicker]').datepicker({
    format: "yyyy-mm-dd"
  });